SET foreign_key_checks = 0;
DELETE FROM role;
DELETE FROM user;
DELETE FROM difficulty;
DELETE FROM grooming_type;
DELETE FROM trail_type;
DELETE FROM trail_report;
DELETE FROM trail;
DELETE FROM location;
SET foreign_key_checks = 1;