SET foreign_key_checks = 0;
DELETE FROM Role;
DELETE FROM User;
DELETE FROM Difficulty;
DELETE FROM GroomingType;
DELETE FROM TrailType;
DELETE FROM TrailReport;
DELETE FROM Trail;
DELETE FROM Location;
DELETE FROM TrailHead;
SET foreign_key_checks = 1;